USE aiport;

ALTER TABLE Tenants
  ADD COLUMN IF NOT EXISTS UsaBloco TINYINT(1) NOT NULL DEFAULT 0 AFTER RamalTransfHumano,
  ADD COLUMN IF NOT EXISTS UsaTorre TINYINT(1) NOT NULL DEFAULT 0 AFTER UsaBloco;
